### ISSUE TITLE
having insane troubles with muti game servers

### ISSUE THREAD

**Issue by mrBoomDev** [johnnyguitarFP/deadmatterdedisetup#1]
trying to use my dedi box but open muti servers i paid for a dedi box to host 3 servers only can get one up i have no idea what to do to get the others up

**Comment by Gaxon1** [comment]
That is due to not being able to change the Steam Query Port. I've asked on Twitter how to change it, but no response. Maybe it's just an oversight and they'll fix it soon. You need two ports, one query port and one rcon port (if enabled) per server. From the readme, it looks like we can only change the primary game port.

**Comment by mrBoomDev** [comment]
It’s so dumb man

**Comment by johnnyguitarFP** [comment]
See the examples on how to change the query ports.

**Comment by mrBoomDev** [comment]
How do I do it I don’t see it at all @johnnyguitarFP

**Comment by JamieKG** [comment]
look at the extra files he has added to the repository
