### ISSUE TITLE
get kick from my server 

### ISSUE THREAD

**Issue by pedui123** [johnnyguitarFP/deadmatterdedisetup#11]
Warning: STEAM: AUTH: User 76561198051969158 failed authentication 4
LogOnline: STEAM: AUTH: Marking 76561198051969158 for kick

**Comment by kidandcat** [comment]
See errors on your server log, it is probably failing to setup the SteamQueryServer socket, and so it cannot authenticate users through steam. I fixed it by changing the steam query server to another port (don't use 27016)

**Comment by Lightning4D** [comment]
I had this same issue, getting kicked because the SteamQuery Port did not work, so not Authentification!
To solve it I changed my SteamQuery Port, removing the error message from the console log.

But now when I try to direct connect to my server from my client machine, it brings me back to the main menu saying "Connection to host lost", and there is no more join attempt message in the console! (When it kicked me before, I had one)

On a different note, ports have been opened (Can run a minecraft server fine on the same ports for example). My Dead Matter server also appears in the server browser, but on my host machine on canyouseeme.org, it states the ports I use are closed!
Any ideas to solve this?

**Comment by pedui123** [comment]
I used the file given as example and now I can connect to my server but I do not see any change on the console when i log in

**Comment by pedui123** [comment]
and i can't find my server in the server list in game

**Comment by pedui123** [comment]
i found this https://www.reddit.com/r/DeadMatter/comments/ifybbb/dead_matter_dedicated_server_setup_guide_using/ Using default ports everything works but i cant find my server in game

**Comment by ameri-asnawi** [comment]
Hi all,
I got everything to work after understanding what I've missed. 
I even used custom port and having no issues.
Sharing my checklist if I start everything again from scratch:

- I've download server with SteamCMD & open with command prompt with -log (or if u have the .bat file, works too)
to run it once for generate the empty ini files, then wait until it does nothing and close it.

- Sign in into Steam Client with Dead Matter Steam Account (download first if you don't have one like me) and i just let it run in the background. **important**

- Config the .ini files with your choice, follow the readme.md

- - Set Game Port
- set port# in engine.ini
- open port or port forward on your router
- Create inbound firewall rule in Advanced Firewall for TCP & UDP with chosen port#

- - Set Steam Query Port
- set port# in engine.ini and game.ini
- open port or port forward on your router
- Create inbound firewall rule in Advanced Firewall for UDP with chosen port#

- Run server executable or batch file again.

I can now see the server because I've missed the Log in into Steam Client part
