### ISSUE TITLE
 I couldn't find my own server

### ISSUE THREAD

**Issue by jackKiZhu** [johnnyguitarFP/deadmatterdedisetup#2]
I ran the server from steam, but I couldn't find my own server.

**Comment by JamieKG** [comment]
Sounds like a Firewall/Port forwarding Issue

**Comment by jackKiZhu** [comment]
> Sounds like a Firewall/Port forwarding Issue

All ports are open and the firewall is closed!

**Comment by johnnyguitarFP** [comment]
Check the output log for Steam API Initialization

**Comment by CHansen42** [comment]
I'm getting this as well. Dedicated server with all ports open. 

`LogSteamShared: Display: Loading Steam SDK 1.47
LogSteamShared: Steam SDK Loaded!
LogOnline: OSS: Creating online subsystem instance for: Steam
LogSteamShared: Warning: Steam Dedicated Server API failed to initialize.
LogOnline: STEAM: [AppId: 0] Game Server API initialized 0
LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable.
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogOnline: Warning: STEAM: Steam API failed to initialize!
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogOnline: OSS: Unable to create OnlineSubsystem module Steam
LogOnline: OSS: Creating online subsystem instance for: NULL`

**Comment by CHansen42** [comment]
I'm getting this as well on a dedicated server with all ports open.

LogSteamShared: Display: Loading Steam SDK 1.47
LogSteamShared: Steam SDK Loaded!
LogOnline: OSS: Creating online subsystem instance for: Steam
LogSteamShared: Warning: Steam Dedicated Server API failed to initialize.
LogOnline: STEAM: [AppId: 0] Game Server API initialized 0
LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable.
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogOnline: Warning: STEAM: Steam API failed to initialize!
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogOnline: OSS: Unable to create OnlineSubsystem module Steam
LogOnline: OSS: Creating online subsystem instance for: NULL

**Comment by johnnyguitarFP** [comment]
Install a steam client and log into an account that owns Dead Matter. You can logoff of this account afterwards and Game Server API Initialized should be 1 instead of 0.
